[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/views/*"
  to = "/views/:splat"
  status = 200

[[redirects]]
  from = "/src/*"
  to = "/src/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist" 